name: Compatibility Issue
description: This is for compatibility issues with apps.
labels: ["compatibility"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Compatibility Issue report! Before you continue filling out the report, please **[read our FAQ](https://github.com/LiveContainer/LiveContainer/issues/265) and [search in GitHub Issues](https://github.com/khanhduytran0/LiveContainer/labels/compatibility) for the app you are experiencing issues with** in case it has already been reported.
        
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: What is the problem? How did you discover it?
      placeholder: Please be concise with your explaination.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Instructions to reproduce
      description: Please include consistent instructions to reproduce the problem to make it easier for us to fix it.
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: What version of LiveContainer and iOS are you using?
      description: To retrieve LiveContainer version, go to LiveContainer settings, then scroll to the bottom of the page.
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Other
      description: If you have any other info that might be useful, or if you found a workaround, please put it here.
